`chore(configs): refine DLM policy reference (copy tags, enabled state)`

Description: "Daily EBS snapshots for dev (3-day retention)"
Target:
  ResourceType: Volume
  Tag: "Backup=dlm-daily"
Schedule:
  Name: "daily-dev-backups"
  Frequency: "daily"
  StartTimeUTC: "00:30"
  RetainCount: 3
Options:
  CopyTagsFromSource: true
  State: "Enabled"     # Enabled | Disabled
Notes:
  - "Keep volumes small in dev to minimize snapshot storage."
  - "Snapshots created by DLM will follow policy retention automatically."
